### ISSUE TITLE
Somtimes it gets too slow while Adding new orders

### ISSUE THREAD

**Issue by mohamadsafi2** [MohamadSafi/market-making-bot#1]
The bot gets slow in the matter of recreating orders the proccess itself is fast but it take too much time to start it!

**Comment by MohamadSafi** [comment]
You can comment the line 177 in the file `src/market_making`
```
time.sleep(get_dynamic_sleep_time(current_volatility))
```
or modify the function `get_dynamic_sleep_time` to get the best sleep time you want.
